spring:
  profiles:
    active: dev,postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        generate_statistics: false
    show-sql: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
liquibase:
  changelog:
    location: classpath:database/changelog-master.xml

com:
  github:
    saphyra:
      skyxplore:
        cacheRepository:
          fullSyncExecutionIntervalInMilliseconds: 60000 #1 minute
          expirationSeconds: 600 #10 minutes
          enabled: true
        game:
          map:
            dimensions:
              x: 2000
              y: 2000
          star:
            creation:
              attempts: 300
              minStarDistance: 148
          citizen:
            initialAmount: 10
          connection:
            maxDistance: 300
            maxNumberOfConnections: 4
          surface:
            minSize: 15
            maxSize: 30
            surfaceTypeSpawnDetails:
            - surfaceName: COAL_MINE
              spawnRate: 1
              optional: true
            - surfaceName: DESERT
              spawnRate: 3
            - surfaceName: FOREST
              spawnRate: 2
            - surfaceName: LAKE
              spawnRate: 1
            - surfaceName: MOUNTAIN
              spawnRate: 2
              optional: false
            - surfaceName: OIL_FIELD
              spawnRate: 1
            - surfaceName: ORE_MINE
              spawnRate: 1
            - surfaceName: VOLCANO
              spawnRate: 2
              optional: true
          humanResource:
            workPoints: 10
          skill:
            initialNextLevel: 1000
            experienceRequirementMultiplier: 2
      authservice:
        auth:
          filter:
            order: 100
          access-token:
            expiration-seconds: 900
            cleanup-interval-cron: 0 * * * * *
          login:
            multiple-login-allowed: false
            path: /api/login
          logout:
            path: /api/logout
          cookie:
            access-token-id: accesstokenid
            user-id: userId
          rest:
            request-type-header: Request-Type
            rest-type-value: rest
        redirection:
          filter:
            order: 90