metrics:
  rest:
    enabled: true
  repository:
    enabled: false
  cacheRepository:
    enabled: false

server:
  tomcat:
    max-threads: 100

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/skyxplore4?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

game:
  devMode: true

logging:
  level:
    com:
      github:
        saphyra:
          skyxplore:
            game:
              map:
                surface:
                  creation: INFO
              system:
                building:
                  creation: INFO