metrics:
  rest:
    enabled: true
  repository:
    enabled: false

server:
  tomcat:
    max-threads: 100

game:
  devMode: true

logging:
  level:
    com:
      github:
        saphyra:
          skyxplore:
            game:
              map:
                surface:
                  creation: INFO
              system:
                building:
                  creation: INFO