spring:
  profiles:
    active: dev
  jpa:
    show-sql: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
liquibase:
  changelog:
    location: classpath:database/changelog-master.xml

com:
  github:
    saphyra:
      authservice:
        auth:
          filter:
            order: 100
          access-token:
            expiration-seconds: 900
            cleanup-interval-cron: 0 * * * * *
          login:
            multiple-login-allowed: false
            path: /api/login
          logout:
            path: /api/logout
          cookie:
            access-token-id: accesstokenid
            user-id: userid
          rest:
            request-type-header: Request-Type
            rest-type-value: rest
        redirection:
          filter:
            order: 90