spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/skyxplore4?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    com:
      github:
        saphyra:
          skyxplore:
            game:
              map:
                surface:
                  creation: INFO