package com.github.saphyra.skyxplore.common;

public enum ErrorCode {
    BAD_CREDENTIALS,
    BUILDING_NOT_FOUND,
    CONSTRUCTION_IN_PROGRESS,
    CONSTRUCTION_NOT_FOUND,
    DATA_NOT_FOUND,
    GAME_NOT_FOUND,
    GENERAL_ERROR,
    INVALID_BUILD_LOCATION,
    INVALID_LOCALE,
    INVALID_STAR_ACCESS,
    MAX_LEVEL_REACHED,
    PLAYER_NOT_FOUND,
    RESEARCH_NOT_PRESENT,
    SESSION_EXPIRED,
    STAR_NOT_FOUND,
    STORAGE_FULL,
    SURFACE_NOT_FOUND,
    TERRAFORMING_ALREADY_IN_PROGRESS,
    TERRAFORMING_NOT_POSSIBLE,
    UPGRADE_ALREADY_IN_PROGRESS,
    USER_NAME_ALREADY_EXISTS,
    USER_NOT_FOUND
}
