package com.github.saphyra.skyxplore.common;

public enum ErrorCode {
    BAD_CREDENTIALS,
    BUILDING_NOT_FOUND,
    DATA_NOT_FOUND,
    GAME_NOT_FOUND,
    GENERAL_ERROR,
    INVALID_BUILD_LOCATION,
    INVALID_GAME_ACCESS,
    INVALID_LOCALE,
    INVALID_STAR_ACCESS,
    PLAYER_NOT_FOUND,
    SESSION_EXPIRED,
    STAR_NOT_FOUND,
    STORAGE_FULL,
    SURFACE_NOT_FOUND,
    USER_NAME_ALREADY_EXISTS,
    USER_NOT_FOUND
}
