spring:
  datasource:
    username: root
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    liquibase: WARN
    org:
      springframework: WARN
      hibernate: WARN
      apache: WARN
    com:
      zaxxer: WARN
      github:
        saphyra:
          exceptionhandling: error
          skyxplore: warn