metrics:
  rest:
    enabled: true
  repository:
    enabled: false
  cacheRepository:
    enabled: false

server:
  tomcat:
    max-threads: 1

game:
  devMode: true

com:
  github:
    saphyra:
      skyxplore:
        cacheRepository:
          enabled: false
        game:
          star:
            creation:
              attempts: 3

logging:
  level:
    com:
      github:
        saphyra:
          skyxplore:
            game:
              map:
                surface:
                  creation: INFO
              system:
                building:
                  creation: INFO